Repository Judy-999/ios-wanted-GyroData, pull requests merged in 2022-12, with the labels that each got.

#4 프로젝트 기본 설정
  GyroData.xcodeproj/project.pbxproj
  GyroData/Base.lproj/Main.storyboard
  GyroData/Info.plist
  GyroData/SceneDelegate.swift
  GyroData/ViewController.swift
Labels: 설정

#7 MotionList Scene 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/SceneDelegate.swift
  GyroData/Scenes/MotionListScene/MotionListViewController.swift
  GyroData/Scenes/MotionListScene/SubViews/MotionListTableViewCell.swift
Labels: 기능, 화면

#9 MotionList Scene내 ViewModel 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Model/Motion.swift
  GyroData/Scenes/MotionListScene/MotionListViewController.swift
  GyroData/Scenes/MotionListScene/MotionListViewModel.swift
  GyroData/Scenes/MotionListScene/SubViews/MotionListTableViewCell.swift
  GyroData/Utility/Observable/Observable.swift
Labels: 기능, 화면

#10 CoreDataManager 및 MotionList Scene내 CoreData 로직 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Domain/Entities/Motion.swift
  GyroData/Domain/Entities/MotionType.swift
  GyroData/Domain/UseCase/MotionCoreDataUseCase.swift
  GyroData/Model/Motion.swift
  GyroData/Scenes/MotionListScene/MotionListViewController.swift
  GyroData/Scenes/MotionListScene/MotionListViewModel.swift
  GyroData/Service/CoreData/CoreDataManager.swift
  GyroData/Service/CoreData/CoreDataStack.swift
  GyroData/Service/CoreData/Entities/MotionInfo+CoreDataClass.swift
  GyroData/Service/CoreData/Entities/MotionInfo+CoreDataProperties.swift
  GyroData/Service/CoreData/Entities/MotionInfo.xcdatamodeld/MotionInfo.xcdatamodel/contents
  GyroData/Service/CoreData/Entities/Storable.swift
Labels: 기능, CoreData

#13 GraphView 및 MotionMeasurementManager 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/GraphView.swift
  GyroData/Scenes/MotionMeasurementScene/MeasurementViewController.swift
  GyroData/Utility/GraphView/Entities/GraphNumber.swift
  GyroData/Utility/GraphView/Entities/MotionData.swift
  GyroData/Utility/GraphView/Extension/CGContext+GridGraph.swift
  GyroData/Utility/GraphView/GraphView.swift
  GyroData/Utility/GraphView/SubViews/GraphSegment.swift
  GyroData/Utility/GraphView/SubViews/MotionLabel.swift
  GyroData/Utility/MeasurementManager/MotionMeasurementManager.swift
  GyroData/Utility/MeasurementManager/Protocol/Measurementable.swift
Labels: 기능

#15 MotionResultScene 및 MotionResultViewModel 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Domain/Entities/MotionInformation.swift
  GyroData/Domain/Entities/MotionResult.swift
  GyroData/Scenes/MotionListScene/MotionListViewController.swift
  GyroData/Scenes/MotionResultScene/MotionResultPlayViewController.swift
  GyroData/Scenes/MotionResultScene/MotionResultViewController.swift
  GyroData/Scenes/MotionResultScene/MotionResultViewModel.swift
  GyroData/Scenes/MotionResultScene/SubViews/PlayButton.swift
Labels: 기능, 화면

#18 FileDataManager 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Domain/Entities/Motion.swift
  GyroData/Domain/Entities/MotionInformation.swift
  GyroData/Domain/Entities/MotionType.swift
  GyroData/Domain/UseCase/MotionFileManagerUseCase.swift
  GyroData/Service/FileManager/FileDataManager.swift
  GyroData/Utility/GraphView/Entities/GraphNumber.swift
Labels: 기능, FileManager

#19 MeasurementScene 및 MotionMeasurementViewModel 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Scenes/MotionMeasurementScene/MeasurementViewController.swift
  GyroData/Scenes/MotionMeasurementScene/MotionMeasurementViewModel.swift
  GyroData/Scenes/MotionMeasurementScene/SubViews/MeasurementButton.swift
  GyroData/Utility/GraphView/GraphView.swift
  GyroData/Utility/MeasurementManager/MotionMeasurementManager.swift
Labels: 기능, 화면

#22 MotionListScene 개선
  GyroData.xcodeproj/project.pbxproj
  GyroData/Domain/UseCase/MotionCoreDataUseCase.swift
  GyroData/Scenes/MotionListScene/MotionListViewController.swift
  GyroData/Scenes/MotionListScene/MotionListViewModel.swift
  GyroData/Scenes/MotionListScene/SubViews/MotionListTableViewCell.swift
  GyroData/Utility/GraphView/Extension/Date+Extension.swift
Labels: 버그, 리팩토링

#23 CoreData 관련 Error처리 및 NavigationBar style 설정
  GyroData.xcodeproj/project.pbxproj
  GyroData/Domain/UseCase/MotionCoreDataUseCase.swift
  GyroData/SceneDelegate.swift
  GyroData/Scenes/MotionListScene/MotionListViewModel.swift
  GyroData/Service/CoreData/CoreDataError.swift
  GyroData/Service/CoreData/CoreDataManager.swift
  GyroData/Service/CoreData/CoreDataStack.swift
Labels: 기능, 리팩토링

#25 FileManager관련 Error처리
  GyroData.xcodeproj/project.pbxproj
  GyroData/Domain/UseCase/MotionFileManagerUseCase.swift
  GyroData/Scenes/MotionListScene/MotionListViewModel.swift
  GyroData/Scenes/MotionMeasurementScene/MeasurementViewController.swift
  GyroData/Scenes/MotionMeasurementScene/MotionMeasurementViewModel.swift
  GyroData/Scenes/MotionResultScene/MotionResultViewController.swift
  GyroData/Scenes/MotionResultScene/MotionResultViewModel.swift
  GyroData/Service/FileManager/FileDataManager.swift
  GyroData/Service/FileManager/FileManagerError.swift
  GyroData/Utility/GraphView/Extension/UIViewController+Extension.swift
Labels: 기능, 리팩토링
